In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame(
    {
        "A": [1,2,3,4,5],
        "B": [10,20,30,40,50],
        "C": [100,200,300,400,500],
        "D": [1000,2000,3000,4000,5000],
    }
)

In [3]:
df1

   A   B    C     D
0  1  10  100  1000
1  2  20  200  2000
2  3  30  300  3000
3  4  40  400  4000
4  5  50  500  5000

In [4]:
df1.shape

(5, 4)

In [5]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
dtypes: int64(4)
memory usage: 288.0 bytes

In [7]:
df1.describe()

              A          B           C           D
count  5.000000   5.000000    5.000000     5.00000
mean   3.000000  30.000000  300.000000  3000.00000
std    1.581139  15.811388  158.113883  1581.13883
min    1.000000  10.000000  100.000000  1000.00000
25%    2.000000  20.000000  200.000000  2000.00000
50%    3.000000  30.000000  300.000000  3000.00000
75%    4.000000  40.000000  400.000000  4000.00000
max    5.000000  50.000000  500.000000  5000.00000

## Applying Functions

In [8]:
def square(x):
    return x**2

In [9]:
df1["B"] = df1["B"].apply(square)

In [10]:
df1

   A     B    C     D
0  1   100  100  1000
1  2   400  200  2000
2  3   900  300  3000
3  4  1600  400  4000
4  5  2500  500  5000

In [11]:
df1["D"] = df1["B"].apply(square)

In [12]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [13]:
df1["D"] = df1["B"].apply(lambda x : x**2)

In [14]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000