# 🐼 Introduction to Pandas

> **What is Pandas?**
>
> Pandas is Python's most popular library for working with **data**. Think of it like Microsoft Excel — but inside Python, way more powerful, and you control everything with code.
>
> The name comes from **"Panel Data"** — a term from statistics for structured data.
>
> ### Why do we need it?
> Raw Python lists and dictionaries are hard to work with when you have thousands of rows of data. Pandas gives you:
> - 📋 **DataFrames** — like spreadsheet tables
> - 📊 **Series** — like a single column of data
> - 🔍 Tools to filter, sort, clean, and analyze data easily
>
> ### 🏠 Analogy
> Imagine you have a huge Excel file with 500 rows of Pakistan population data. In regular Python, accessing and analyzing it would be a nightmare. With Pandas, you can do it in one line.

## ⚙️ Environment Check

Before doing anything, we check that our Python environment is set up correctly.
- `sys.executable` → shows which Python is being used
- `openpyxl` → a library Pandas needs to read/write Excel files (`.xlsx`)

In [1]:
import sys
print(f"Python executable: {sys.executable}")
print(f"Python version: {sys.version}")

# Try to import openpyxl — needed for reading/writing Excel files
try:
    import openpyxl
    print(f"✅ openpyxl version: {openpyxl.__version__} found!")
except ImportError:
    print("❌ openpyxl NOT found in this kernel")
    print("Fix: run  pip install openpyxl  in your terminal")

Python executable: /home/waseem-dev/miniconda3/envs/ai_env/bin/python
Python version: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]
✅ openpyxl version: 3.1.5 found!

## 📌 Your First Series

A **Series** is the simplest Pandas object — it's just a list of values with an **index** (row numbers) attached automatically.

Think of it like a single column in Excel:
```
| Index | Value |
| ----: | ----: |
|     0 |     1 |
|     1 |     2 |
|     2 |     3 |
|     3 |     4 |
|     4 |     5 |
```

In [2]:
import pandas as pd
import os

a = [1, 2, 3, 4, 5]

myFirstSeries = pd.Series(a)

print(f"First element (index 0): {myFirstSeries[0]}")
print()
print("The full Series:")
print(myFirstSeries)
print()
print("Notice: Pandas automatically added index numbers (0, 1, 2, 3, 4) on the left!")

First element (index 0): 1

The full Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Notice: Pandas automatically added index numbers (0, 1, 2, 3, 4) on the left!

---
## 📥 Importing a Real Dataset

Now the fun part — loading real data. We're using `kagglehub` to download a **Pakistan Population Dataset** from Kaggle (a popular data science platform).

This dataset has population data for every **tehsil (sub-division)** in Pakistan from the 2017 census.

In [3]:
import kagglehub

# Download the dataset — kagglehub caches it locally so it only downloads once
path = kagglehub.dataset_download("mabdullahsajid/population-of-pakistan-dataset")

print("✅ Dataset downloaded!")
print(f"Saved at: {path}")

✅ Dataset downloaded!
Saved at: /home/waseem-dev/.cache/kagglehub/datasets/mabdullahsajid/population-of-pakistan-dataset/versions/1

### 📖 Reading the CSV File

`pd.read_csv()` loads a CSV file into a **DataFrame** — a table with rows and columns, just like Excel.

- `df.head()` → shows the **first 5 rows** (like peeking at the top of the file)
- `df.tail()` → shows the **last 5 rows**
- `pd.concat([...])` → **combines** two DataFrames vertically (stacks them)

In [4]:
df = pd.read_csv("./Datasets/population.csv")

dfHead = df.head()   # First 5 rows
dfTail = df.tail()   # Last 5 rows

# Combine first and last 5 rows to see both ends of the data
dfMerged = pd.concat([dfHead, dfTail])

print(f"Total rows in dataset: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print()
print("First 5 + Last 5 rows:")
dfMerged

Total rows in dataset: 528
Total columns: 21

First 5 + Last 5 rows:

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48
523,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,110.25,...,72063,1.64,0,0,0,0,0.00,0.00,0,0.00
524,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,111.03,...,31472,2.93,0,0,0,0,0.00,0.00,0,0.00
525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,109.96,...,37708,0.95,0,0,0,0,0.00,0.00,0,0.00
526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,119.68,...,36508,1.71,0,0,0,0,0.00,0.00,0,0.00
527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,113.30,...,90772,2.79,0,0,0,0,0.00,0.00,0,0.00

### 💾 Saving to Excel

`df.to_excel()` exports your DataFrame to a `.xlsx` Excel file — great for sharing data with people who use Excel.

- `index=False` → don't include the row numbers (0, 1, 2...) in the file
- `sheet_name=` → name of the Excel sheet tab

In [5]:
# Create the export folder if it doesn't already exist
if not os.path.exists("./Exported_Data"):
    os.makedirs("./Exported_Data")
    print("📁 Created folder: ./Exported_Data")

# Save DataFrame to Excel
df.to_excel("./Exported_Data/new_data.xlsx", index=False, sheet_name="Population_Data")
print("✅ Saved to Excel!")

# Read it back and verify
df_xl = pd.read_excel("./Exported_Data/new_data.xlsx")
print(f"✅ Read back from Excel. Shape: {df_xl.shape}  → ({df_xl.shape[0]} rows, {df_xl.shape[1]} columns)")

✅ Saved to Excel!
✅ Read back from Excel. Shape: (528, 21)  → (528 rows, 21 columns)

---
## 🔍 Exploring the DataFrame

These are the most commonly used tools to **understand a new dataset** quickly.

In [6]:
# .info() → Quick summary: column names, data types, and how many non-null values
# This tells you: "What columns do I have? Any missing data?"
print("=== df.info() ===")
df.info()

=== df.info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROVINCE                    528 non-null    object
 1   DIVISION                    528 non-null    object
 2   DISTRICT                    528 non-null    object
 3   SUB DIVISION                528 non-null    object
 4   AREA (sq.km)                528 non-null    float64
 5   ALL SEXES (RURAL)           528 non-null    int64
 6   MALE (RURAL)                528 non-null    int64
 7   FEMALE (RURAL)              528 non-null    int64
 8   TRANSGENDER (RURAL)         528 non-null    int64
 9   SEX RATIO (RURAL)           528 non-null    float64
 10  AVG HOUSEHOLD SIZE (RURAL)  528 non-null    float64
 11  POPULATION 1998 (RURAL)     528 non-null    int64
 12  ANNUAL GROWTH RATE (RURAL)  528 non-null    float64
 13  ALL SEXES (URBAN)           528 non-null    int64
 14  MALE (URBAN)                528 non-null    int64
 15  FEMALE (URBAN)              528 non-null    int64
 16  TRANSGENDER (URBAN)         528 non-null    int64
 17  SEX RATIO (URBAN)           528 non-null    float64
 18  AVG HOUSEHOLD SIZE (URBAN)  528 non-null    float64
 19  POPULATION 1998 (URBAN)     528 non-null    int64
 20  ANNUAL GROWTH RATE (URBAN)  528 non-null    float64
dtypes: float64(7), int64(10), object(4)
memory usage: 86.8+ KB

In [7]:
# Accessing a single column — two ways to do it:
# Way 1: df.COLUMN_NAME  (dot notation — works when column name has no spaces)
# Way 2: df["COLUMN_NAME"]  (bracket notation — always works)

print("All unique provinces in the dataset:")
print(df.PROVINCE.unique())  # .unique() removes duplicates
print()
print("How many times each province appears:")
print(df.PROVINCE.value_counts())

All unique provinces in the dataset:
['PUNJAB' 'SINDH' 'BALOCHISTAN' 'KPK' 'KPK/FATA']

How many times each province appears:
PROVINCE
PUNJAB         143
SINDH          137
BALOCHISTAN    131
KPK             71
KPK/FATA        46
Name: count, dtype: int64

In [8]:
# Selecting MULTIPLE columns at once — pass a LIST of column names
# This gives you a smaller table with only the columns you care about
subset = df[["PROVINCE", "DISTRICT", "ALL SEXES (RURAL)"]]
print(f"Showing 3 out of {len(df.columns)} columns:")
subset.head(10)

Showing 3 out of 21 columns:

  PROVINCE               DISTRICT  ALL SEXES (RURAL)
0   PUNJAB  BAHAWALNAGAR DISTRICT             619550
1   PUNJAB  BAHAWALNAGAR DISTRICT             540342
2   PUNJAB  BAHAWALNAGAR DISTRICT             361240
3   PUNJAB  BAHAWALNAGAR DISTRICT             382115
4   PUNJAB  BAHAWALNAGAR DISTRICT             452723
5   PUNJAB    BAHAWALPUR DISTRICT             902476
6   PUNJAB    BAHAWALPUR DISTRICT                  0
7   PUNJAB    BAHAWALPUR DISTRICT             467938
8   PUNJAB    BAHAWALPUR DISTRICT             340747
9   PUNJAB    BAHAWALPUR DISTRICT             221431

In [9]:
# Useful properties to inspect your DataFrame:
print("All column names:")
print(df.columns.tolist())
print()

# Shape = (rows, columns)
print(f"Shape: {df.shape}")
print(f"  → {df.shape[0]} rows (tehsils/sub-divisions)")
print(f"  → {df.shape[1]} columns")
print()

# len() also gives number of rows
print(f"Number of rows via len(): {len(df)}")

All column names:
['PROVINCE', 'DIVISION', 'DISTRICT', 'SUB DIVISION', 'AREA (sq.km)', 'ALL SEXES (RURAL)', 'MALE (RURAL)', 'FEMALE (RURAL)', 'TRANSGENDER (RURAL)', 'SEX RATIO (RURAL)', 'AVG HOUSEHOLD SIZE (RURAL)', 'POPULATION 1998 (RURAL)', 'ANNUAL GROWTH RATE (RURAL)', 'ALL SEXES (URBAN)', 'MALE (URBAN)', 'FEMALE (URBAN)', 'TRANSGENDER (URBAN)', 'SEX RATIO (URBAN)', 'AVG HOUSEHOLD SIZE (URBAN)', 'POPULATION 1998 (URBAN)', 'ANNUAL GROWTH RATE (URBAN)']

Shape: (528, 21)
  → 528 rows (tehsils/sub-divisions)
  → 21 columns

Number of rows via len(): 528

In [10]:
# .describe() → Statistical summary of ALL numeric columns at once
# Shows: count, mean, std, min, 25th percentile, median (50%), 75th percentile, max
# This is a great first look at the data to spot unusual values
print("Statistical summary (numeric columns only):")
df.describe()

Statistical summary (numeric columns only):

,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),AVG HOUSEHOLD SIZE (RURAL),POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
count,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000
mean,1492.005871,2.462780e+05,1.252757e+05,1.209841e+05,18.174242,98.982614,6.277064,1.674280e+05,3.124792,1.408635e+05,7.284339e+04,6.799787e+04,22.276515,75.411269,4.406402,8.014457e+04,1.920814
std,2039.453778,2.711898e+05,1.375630e+05,1.337169e+05,25.522248,26.812660,2.074947,1.783890e+05,9.577872,3.512463e+05,1.823492e+05,1.688725e+05,66.068127,49.687341,2.948336,2.023120e+05,2.098908
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,425.000000,5.093450e+04,2.712725e+04,2.397900e+04,1.000000,101.105000,5.700000,3.527350e+04,1.440000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,882.000000,1.652410e+05,8.413450e+04,8.204400e+04,10.000000,105.285000,6.310000,1.172065e+05,2.030000,4.325450e+04,2.198000e+04,2.099900e+04,3.000000,103.195000,5.755000,2.129800e+04,1.855000
75%,1734.250000,3.129112e+05,1.605022e+05,1.522190e+05,25.000000,108.347500,7.200000,2.130542e+05,2.812500,1.178148e+05,6.030175e+04,5.746525e+04,19.000000,107.040000,6.340000,6.542225e+04,2.985000
max,18374.000000,2.297375e+06,1.172995e+06,1.124167e+06,213.000000,139.380000,12.430000,1.044035e+06,100.000000,3.653616e+06,1.905921e+06,1.746900e+06,795.000000,297.810000,10.060000,2.075867e+06,19.780000