# 📋 Pandas DataFrames

> **What is a DataFrame?**
>
> A DataFrame is a **2D table** — rows and columns — exactly like an Excel spreadsheet.
>
> ```
>     calories  duration
>  0     420        50
>  1     380        40
>  2     390        45
>  ↑
>  index (row labels)
> ```
>
> Every column in a DataFrame is a **Series**. The DataFrame is just multiple Series glued together.
>
> ### The two main ways to select data:
> | Method | What it does | Example |
> |---|---|---|
> | `df.loc[]` | Select by **label/name** | `df.loc[0]`, `df.loc["Day 1"]` |
> | `df.iloc[]` | Select by **position number** | `df.iloc[0]` = always first row |

## creating DataFrames

In [83]:
import pandas as pd
import numpy as np
data_dict = {
    "Name": ["Waseem", "Summiya", "Kamran", "Talha"],
    "Age": [12, 13, 14, 15],
    "City": ["Quetta", "Karachi", "Khuzdar", "Kuchlak"],
    "Salary": [65000, 70000, 62000, 85000]
}

pd.DataFrame(data_dict)

      Name  Age     City  Salary
0   Waseem   12   Quetta   65000
1  Summiya   13  Karachi   70000
2   Kamran   14  Khuzdar   62000
3    Talha   15  Kuchlak   85000

## Method 1: Provide index while creating DataFrame

In [84]:
data_list = [
    ["Waseem", 12, "Quetta", 65000],
    ["Summiya", 13, "Karachi", 70000],
    ["Kamran", 14, "Quetta", 65000],
    ["Talha", 15, "Kuchlak", 65000]
]
columns = ["Name", "Age", "City", "Salary"]
index_labels = ["A", "B", "C", "D"]
data_list
df_01 = pd.DataFrame(data_list,  columns=columns, index=index_labels)
df_01

      Name  Age     City  Salary
A   Waseem   12   Quetta   65000
B  Summiya   13  Karachi   70000
C   Kamran   14   Quetta   65000
D    Talha   15  Kuchlak   65000

## Method 2: Change index later

In [85]:
my_new_df_with_indexes_changed_later = pd.DataFrame(data_list)
my_new_df_with_indexes_changed_later.index = ["row1", "row2", "row3", "row4"]
my_new_df_with_indexes_changed_later

            0   1        2      3
row1   Waseem  12   Quetta  65000
row2  Summiya  13  Karachi  70000
row3   Kamran  14   Quetta  65000
row4    Talha  15  Kuchlak  65000

## Method 3: Set a column as index (VERY IMPORTANT 🔥)

In [86]:
my_new_df_with_indexes_changed_later = pd.DataFrame(data_list, columns=columns)
my_new_df_with_indexes_changed_later.set_index("Name", inplace=True) # inplace = True means change the actual dataset
# inplace=False → return a modified copy and leave the original unchanged.
my_new_df_with_indexes_changed_later

         Age     City  Salary
Name
Waseem    12   Quetta   65000
Summiya   13  Karachi   70000
Kamran    14   Quetta   65000
Talha     15  Kuchlak   65000

## Selection of Columns

In [87]:
df_01[["Name", "City"]]

      Name     City
A   Waseem   Quetta
B  Summiya  Karachi
C   Kamran   Quetta
D    Talha  Kuchlak

## Adding New Column

In [88]:
df_01["Designation"] = ["Web-Developer", "Doctor", "Desktop App Developer", "Mobile App Developer"]
df_01

      Name  Age     City  Salary            Designation
A   Waseem   12   Quetta   65000          Web-Developer
B  Summiya   13  Karachi   70000                 Doctor
C   Kamran   14   Quetta   65000  Desktop App Developer
D    Talha   15  Kuchlak   65000   Mobile App Developer

## Removing Column

In [89]:
df_01.drop("Age", axis=1) # axis 0 means it will search the rows not columns
# But this method will only remove its copy and won't remove it from RAM, so for that we will use inplace=True property

      Name     City  Salary            Designation
A   Waseem   Quetta   65000          Web-Developer
B  Summiya  Karachi   70000                 Doctor
C   Kamran   Quetta   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

In [90]:
df_01.drop("Age", axis=1, inplace=True)

In [91]:
df_01

      Name     City  Salary            Designation
A   Waseem   Quetta   65000          Web-Developer
B  Summiya  Karachi   70000                 Doctor
C   Kamran   Quetta   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

## Deleting Rows

In [92]:
df_01.drop("A", axis=0)

      Name     City  Salary            Designation
B  Summiya  Karachi   70000                 Doctor
C   Kamran   Quetta   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

In [93]:
df_01.loc["B"] # Get the row whose index label is "B".

Name           Summiya
City           Karachi
Salary           70000
Designation     Doctor
Name: B, dtype: object

In [94]:
df_01.loc[df_01["City"] == "Quetta", "Name"] # Give me the Name column where the city is Quetta.

A    Waseem
C    Kamran
Name: Name, dtype: object

In [95]:
df_01

      Name     City  Salary            Designation
A   Waseem   Quetta   65000          Web-Developer
B  Summiya  Karachi   70000                 Doctor
C   Kamran   Quetta   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

In [96]:
df_01.iloc[[0, 3]] # Get rows at position 0 and position 3.

     Name     City  Salary           Designation
A  Waseem   Quetta   65000         Web-Developer
D   Talha  Kuchlak   65000  Mobile App Developer

All rows but first column

In [97]:
df_01.iloc[:, 0] # Give me all rows from column 0.

A     Waseem
B    Summiya
C     Kamran
D      Talha
Name: Name, dtype: object

In [98]:
df_01.iloc[0, 2] = 20500000 # Change the value from the cell where row is the first one (row 0) and column is the third (column 2)

In [99]:
df_new = df_01["City"] == "Quetta"
df_new

A     True
B    False
C     True
D    False
Name: City, dtype: bool

In [100]:
df_01.loc["A":"C", ["Name", "Salary"]] # Gimme Name and Salary column from rows A-C

      Name    Salary
A   Waseem  20500000
B  Summiya     70000
C   Kamran     65000

In [101]:
df_01.iloc[0:2, 0:2] # So you get the first 2 rows and first 2 columns.

      Name     City
A   Waseem   Quetta
B  Summiya  Karachi

In [102]:
df_01.iloc[0:3] # Only rows are specified.

      Name     City    Salary            Designation
A   Waseem   Quetta  20500000          Web-Developer
B  Summiya  Karachi     70000                 Doctor
C   Kamran   Quetta     65000  Desktop App Developer

In [103]:
df_01.iloc[0, 0]     # First row, first column

'Waseem'

In [104]:
df_01.iloc[-1]   # last row

Name                          Talha
City                        Kuchlak
Salary                        65000
Designation    Mobile App Developer
Name: D, dtype: object

In [105]:
df_01.iloc[0:3:2]   # works

     Name    City    Salary            Designation
A  Waseem  Quetta  20500000          Web-Developer
C  Kamran  Quetta     65000  Desktop App Developer

In [106]:
new_data = [
    ["Ahmed", "Turbat", 250000, "Data Scientist"],  
    ["Zain", "Quetta", 180000, "ML Engineer"],
    ["Bilal", "Khuzdar", 120000, "Software Developer"],
    ["Hassan", "Gwadar", 200000, "AI Engineer"]
]

correct_columns = ["Name", "City", "Salary", "Designation"]

df_02 = pd.DataFrame(new_data, index=index_labels, columns=correct_columns)
df_03 = pd.concat([df_01, df_02])
df_03

      Name     City    Salary            Designation
A   Waseem   Quetta  20500000          Web-Developer
B  Summiya  Karachi     70000                 Doctor
C   Kamran   Quetta     65000  Desktop App Developer
D    Talha  Kuchlak     65000   Mobile App Developer
A    Ahmed   Turbat    250000         Data Scientist
B     Zain   Quetta    180000            ML Engineer
C    Bilal  Khuzdar    120000     Software Developer
D   Hassan   Gwadar    200000            AI Engineer

In [107]:
df_03.describe()

             Salary
count  8.000000e+00
mean   2.681250e+06
std    7.200197e+06
min    6.500000e+04
25%    6.875000e+04
50%    1.500000e+05
75%    2.125000e+05
max    2.050000e+07

In [108]:
df_03.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, A to D
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         8 non-null      object
 1   City         8 non-null      object
 2   Salary       8 non-null      int64
 3   Designation  8 non-null      object
dtypes: int64(1), object(3)
memory usage: 320.0+ bytes

In [109]:
df_03.loc[["A", "B"], ["Name", "Salary"]]

      Name    Salary
A   Waseem  20500000
A    Ahmed    250000
B  Summiya     70000
B     Zain    180000

In [110]:
df_03[["Name", "Salary"]][df_03["Salary"] > 70000]

     Name    Salary
A  Waseem  20500000
A   Ahmed    250000
B    Zain    180000
C   Bilal    120000
D  Hassan    200000

In [111]:
df_03[df_03["Salary"] > 70000]

     Name     City    Salary         Designation
A  Waseem   Quetta  20500000       Web-Developer
A   Ahmed   Turbat    250000      Data Scientist
B    Zain   Quetta    180000         ML Engineer
C   Bilal  Khuzdar    120000  Software Developer
D  Hassan   Gwadar    200000         AI Engineer

In [112]:
df_03[["Name", "Salary"]][(df_03["Salary"] > 70000) & (df_03["City"] == "Quetta")]

     Name    Salary
A  Waseem  20500000
B    Zain    180000

In [113]:
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print("Our DataFrame:")
print(df)
print()
print(f"Shape: {df.shape}  →  {df.shape[0]} rows, {df.shape[1]} columns")

Our DataFrame:
   calories  duration
0       420        50
1       380        40
2       390        45

Shape: (3, 2)  →  3 rows, 2 columns

---
## 📍 Selecting Rows with `.loc[]`

`.loc[]` selects rows by their **index label**.

By default the labels are 0, 1, 2... but later we'll give them custom names like "Day 1", "Day 2".

### 🏠 Analogy
`.loc[]` is like finding a person by their **name** in a contact list. You say "give me the row labeled **0**".

In [114]:
# Get a single row by its label
print("Row at label 0:")
print(df.loc[0])
print()
print("Row at label 1:")
print(df.loc[1])

Row at label 0:
calories    420
duration     50
Name: 0, dtype: int64

Row at label 1:
calories    380
duration     40
Name: 1, dtype: int64

In [115]:
# Get MULTIPLE rows — pass a range
# IMPORTANT: df.loc[0:1] includes BOTH 0 and 1 (unlike normal Python slicing!)
print("Rows 0 and 1 (both included):")
print(df.loc[0:1])
print()
print("⚠️  Note: df.loc[0:1] gives 2 rows (0 AND 1). In regular Python, 0:1 would only give index 0!")

Rows 0 and 1 (both included):
   calories  duration
0       420        50
1       380        40

⚠️  Note: df.loc[0:1] gives 2 rows (0 AND 1). In regular Python, 0:1 would only give index 0!

### 🎯 Getting a Specific Cell

You can pinpoint an exact cell using `.loc[row, column]`.

Like GPS coordinates — row first, then column.

In [116]:
# df.loc[row_label, column_name]
print(f"Row 0, calories column: {df.loc[0, 'calories']}")
print(f"Row 1, duration column: {df.loc[1, 'duration']}")
print()
print("\n************ Full table for reference ************")
print(df)

Row 0, calories column: 420
Row 1, duration column: 40


************ Full table for reference ************
   calories  duration
0       420        50
1       380        40
2       390        45

---
## 🔎 Filtering Rows by Condition

This is one of the most useful features in Pandas — filter rows based on a condition, like asking: **"show me only rows where calories == 420"**.

### 🏠 Analogy
Like using a filter in Excel — you click the dropdown and say "show me only rows where calories > 385". Pandas does this with one line of code.

In [117]:
# Filter: only rows where calories == 420
print("Rows where calories == 420:")
print(df.loc[df['calories'] == 420])
print()

# Filter: only rows where calories > 385
print("Rows where calories > 385:")
print(df.loc[df['calories'] > 385])
print()
print("💡 How this works internally:")
print("  df['calories'] > 385  produces:", list(df['calories'] > 385))
print("  → True/False for each row. .loc[] keeps only the True rows.")

Rows where calories == 420:
   calories  duration
0       420        50

Rows where calories > 385:
   calories  duration
0       420        50
2       390        45

💡 How this works internally:
  df['calories'] > 385  produces: [True, False, True]
  → True/False for each row. .loc[] keeps only the True rows.

---
## 🔢 Selecting by Position with `.iloc[]`

`.iloc[]` selects by **position** — always 0, 1, 2... regardless of what the index labels are.

### `.loc[]` vs `.iloc[]` — What's the difference?

```python
# If your DataFrame has custom labels like "Day 1", "Day 2":
# df.loc["Day 1"]   ✅  finds the row LABELED "Day 1"
# df.iloc[0]        ✅  finds the FIRST row (position 0), whatever it is labeled
```

**Use `.iloc[]` when you want to say "give me the 3rd row" regardless of its name.**

In [119]:
# iloc[0] always = first row (position 0)
print("First row by position (iloc[0]):")
print(df.iloc[0])
print()

# Pick specific rows by position — pass a list
print("Rows at positions [1, 2, 0] — notice custom order:")
print(df.loc[[1, 2, 0]])  # You can even reorder!
print()
print("💡 df.loc[[1,2,0]] lets you pick rows in any order you want")

First row by position (iloc[0]):
calories    420
duration     50
Name: 0, dtype: int64

Rows at positions [1, 2, 0] — notice custom order:
   calories  duration
1       380        40
2       390        45
0       420        50

💡 df.loc[[1,2,0]] lets you pick rows in any order you want

---
## 🏷️ Named Indexes (Custom Row Labels)

Instead of 0, 1, 2 as row labels, you can give meaningful names like "Day 1", "Day 2", "Day 3".

This makes `.loc[]` much more readable — you access rows by their **meaning**, not just a number.

In [ ]:
data1 = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

# Give each row a meaningful name
newDf = pd.DataFrame(data1, index=["Day 1", "Day 2", "Day 3"])

print("DataFrame with named row indexes:")
print(newDf)
print()

# Now access rows by their name!
print('newDf.loc["Day 2"]:')  
print(newDf.loc["Day 2"])

DataFrame with named row indexes:
       calories  duration
Day 1       420        50
Day 2       380        40
Day 3       390        45

newDf.loc["Day 2"]:
calories    380
duration     40
Name: Day 2, dtype: int64

---
## 📁 Loading a CSV File into a DataFrame

`pd.read_csv()` is how you bring in real-world data. CSV (Comma-Separated Values) is the most common data format — every tool from Excel to databases can export to CSV.

In [ ]:
populationDf = pd.read_csv("./Datasets/population.csv")

print(f"Loaded: {populationDf.shape[0]} rows × {populationDf.shape[1]} columns")
print()
print("First 5 rows:")
populationDf.head()

Loaded: 528 rows × 21 columns

First 5 rows:

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48