In [1]:
import numpy as np
import pandas as pd

In [15]:
data = {
    "A": [1,2, np.nan, 4, 5],
    "B": [1,np.nan, 3, 4, 5],
    "C": [1,2, 3, np.nan, 5],
    "D": [np.nan,2, 3, 4, 5],
    "E": [1,2, 3, 4, np.nan]
}
df = pd.DataFrame(data)
df

     A    B    C    D    E
0  1.0  1.0  1.0  NaN  1.0
1  2.0  NaN  2.0  2.0  2.0
2  NaN  3.0  3.0  3.0  3.0
3  4.0  4.0  NaN  4.0  4.0
4  5.0  5.0  5.0  5.0  NaN

In [7]:
df.isna()

       A      B      C      D      E
0  False  False  False   True  False
1  False   True  False  False  False
2   True  False  False  False  False
3  False  False   True  False  False
4  False  False  False  False   True

In [8]:
df.isna().sum()

A    1
B    1
C    1
D    1
E    1
dtype: int64

In [9]:
df.isna().any()

A    True
B    True
C    True
D    True
E    True
dtype: bool

In [10]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [12]:
df.dropna(thresh=3)  # it says atleast three "nan" values

     A    B    C    D    E
0  1.0  1.0  1.0  NaN  1.0
1  2.0  NaN  2.0  2.0  2.0
2  NaN  3.0  3.0  3.0  3.0
3  4.0  4.0  NaN  4.0  4.0
4  5.0  5.0  5.0  5.0  NaN

In [14]:
mean = np.mean(df)
df.fillna(mean, inplace=True)

     A    B    C    D    E
0  1.0  1.0  1.0  3.0  1.0
1  2.0  3.0  2.0  2.0  2.0
2  3.0  3.0  3.0  3.0  3.0
3  4.0  4.0  3.0  4.0  4.0
4  5.0  5.0  5.0  5.0  3.0

In [19]:
mean = np.mean(df)
df.fillna(mean)

     A    B    C    D    E
0  1.0  1.0  1.0  3.0  1.0
1  2.0  3.0  2.0  2.0  2.0
2  3.0  3.0  3.0  3.0  3.0
3  4.0  4.0  3.0  4.0  4.0
4  5.0  5.0  5.0  5.0  3.0

In [20]:
values = {
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "E": 4
}
df.fillna(value=values)

     A    B    C    D    E
0  1.0  1.0  1.0  3.0  1.0
1  2.0  1.0  2.0  2.0  2.0
2  0.0  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  4.0  4.0
4  5.0  5.0  5.0  5.0  4.0