# Pandas Dataframes

In [2]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

## Locate Row

In [9]:
df.loc[0]

calories    420
duration     50
Name: 0, dtype: int64

In [10]:
df.loc[0]       # row 0 → calories=420, duration=50
df.loc[1]       # row 1 → calories=380, duration=40

calories    380
duration     40
Name: 1, dtype: int64

### Get multiple rows:

In [14]:
df.loc[0:1]

   calories  duration
0       420        50
1       380        40

### Get Specific Cell

In [17]:
df.loc[0, 'calories']
df.loc[1, 'duration']

np.int64(40)

### Filter by condition

In [18]:
df.loc[df['calories'] == 420]

   calories  duration
0       420        50

In [19]:
df.loc[df['calories'] > 385]

   calories  duration
0       420        50
2       390        45

In [23]:
df.iloc[0]

calories    420
duration     50
Name: 0, dtype: int64

In [26]:
df.loc[[1, 2, 0]]

   calories  duration
1       380        40
2       390        45
0       420        50

### Named Indexes

In [28]:
data1 = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

newDf = pd.DataFrame(data, index=["Day 1)", "Day 2)", "Day 3)"])
newDf

        calories  duration
Day 1)       420        50
Day 2)       380        40
Day 3)       390        45

### Locate Named Indexes

In [30]:
newDf.loc["Day 2)"]

calories    380
duration     40
Name: Day 2), dtype: int64

## Load Files Into a DataFrame

In [32]:
populationDf = pd.read_csv("./Datasets/population.csv")
populationDf

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,110.25,...,72063,1.64,0,0,0,0,0.00,0.00,0,0.00
524,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,111.03,...,31472,2.93,0,0,0,0,0.00,0.00,0,0.00
525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,109.96,...,37708,0.95,0,0,0,0,0.00,0.00,0,0.00
526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,119.68,...,36508,1.71,0,0,0,0,0.00,0.00,0,0.00
527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,113.30,...,90772,2.79,0,0,0,0,0.00,0.00,0,0.00