# 📋 Pandas DataFrames

> **What is a DataFrame?**
>
> A DataFrame is a **2D table** — rows and columns — exactly like an Excel spreadsheet.
>
> ```
>     calories  duration
>  0     420        50
>  1     380        40
>  2     390        45
>  ↑
>  index (row labels)
> ```
>
> Every column in a DataFrame is a **Series**. The DataFrame is just multiple Series glued together.
>
> ### The two main ways to select data:
> | Method | What it does | Example |
> |---|---|---|
> | `df.loc[]` | Select by **label/name** | `df.loc[0]`, `df.loc["Day 1"]` |
> | `df.iloc[]` | Select by **position number** | `df.iloc[0]` = always first row |

## creating DataFrames

In [1]:
import pandas as pd
import numpy as np
data_dict = {
    "Name": ["Waseem", "Summiya", "Kamran", "Talha"],
    "Age": [12, 13, 14, 15],
    "City": ["Quetta", "Karachi", "Khuzdar", "Kuchlak"],
    "Salary": [65000, 70000, 62000, 85000]
}

pd.DataFrame(data_dict)

      Name  Age     City  Salary
0   Waseem   12   Quetta   65000
1  Summiya   13  Karachi   70000
2   Kamran   14  Khuzdar   62000
3    Talha   15  Kuchlak   85000

## Method 1: Provide index while creating DataFrame

In [2]:
data_list = [
    ["Waseem", 12, "Quetta", 65000],
    ["Summiya", 13, "Karachi", 70000],
    ["Kamran", 14, "Khuzdar", 65000],
    ["Talha", 15, "Kuchlak", 65000]
]
columns = ["Name", "Age", "City", "Salary"]
index_labels = ["A", "B", "C", "D"]
data_list
df_01 = pd.DataFrame(data_list,  columns=columns, index=index_labels)
df_01

      Name  Age     City  Salary
A   Waseem   12   Quetta   65000
B  Summiya   13  Karachi   70000
C   Kamran   14  Khuzdar   65000
D    Talha   15  Kuchlak   65000

## Method 2: Change index later

In [3]:
my_new_df_with_indexes_changed_later = pd.DataFrame(data_list)
my_new_df_with_indexes_changed_later.index = ["row1", "row2", "row3", "row4"]
my_new_df_with_indexes_changed_later

            0   1        2      3
row1   Waseem  12   Quetta  65000
row2  Summiya  13  Karachi  70000
row3   Kamran  14  Khuzdar  65000
row4    Talha  15  Kuchlak  65000

## Method 3: Set a column as index (VERY IMPORTANT 🔥)

In [4]:
my_new_df_with_indexes_changed_later = pd.DataFrame(data_list, columns=columns)
my_new_df_with_indexes_changed_later.set_index("Name", inplace=True)
my_new_df_with_indexes_changed_later

         Age     City  Salary
Name
Waseem    12   Quetta   65000
Summiya   13  Karachi   70000
Kamran    14  Khuzdar   65000
Talha     15  Kuchlak   65000

## Selection of Columns

In [5]:
df_01[["Name", "City"]]

      Name     City
A   Waseem   Quetta
B  Summiya  Karachi
C   Kamran  Khuzdar
D    Talha  Kuchlak

## Adding New Column

In [6]:
df_01["Designation"] = ["Web-Developer", "Doctor", "Desktop App Developer", "Mobile App Developer"]
df_01

      Name  Age     City  Salary            Designation
A   Waseem   12   Quetta   65000          Web-Developer
B  Summiya   13  Karachi   70000                 Doctor
C   Kamran   14  Khuzdar   65000  Desktop App Developer
D    Talha   15  Kuchlak   65000   Mobile App Developer

## Removing Column

In [7]:
df_01.drop("Age", axis=1) # axis 0 means it will search the rows not columns
# But this method will only remove its copy and won't remove it from RAM, so for that we will use inplace=True property

      Name     City  Salary            Designation
A   Waseem   Quetta   65000          Web-Developer
B  Summiya  Karachi   70000                 Doctor
C   Kamran  Khuzdar   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

In [8]:
df_01.drop("Age", axis=1, inplace=True)

In [9]:
df_01

      Name     City  Salary            Designation
A   Waseem   Quetta   65000          Web-Developer
B  Summiya  Karachi   70000                 Doctor
C   Kamran  Khuzdar   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

## Deleting Rows

In [ ]:
df_01.drop("A", axis=0)

      Name     City  Salary            Designation
B  Summiya  Karachi   70000                 Doctor
C   Kamran  Khuzdar   65000  Desktop App Developer
D    Talha  Kuchlak   65000   Mobile App Developer

In [17]:
df_01.loc["A"]

Name                  Waseem
City                  Quetta
Salary                 65000
Designation    Web-Developer
Name: A, dtype: object

In [22]:
df_01.loc[df_01["City"] == "Quetta", "Name"]

A    Waseem
Name: Name, dtype: str

In [27]:
df_01.iloc[[0,3]]

     Name     City  Salary           Designation
A  Waseem   Quetta   65000         Web-Developer
D   Talha  Kuchlak   65000  Mobile App Developer

All rows but first column

In [29]:
df_01.iloc[:, 0]

A     Waseem
B    Summiya
C     Kamran
D      Talha
Name: Name, dtype: str

In [30]:
df_01.iloc[0, 2] = 20500000

In [35]:
df_new = df_01["City"] == "Quetta"
df_new

A     True
B    False
C    False
D    False
Name: City, dtype: bool

In [37]:
df_01.loc["A":"C", ["Name", "Salary"]]

      Name    Salary
A   Waseem  20500000
B  Summiya     70000
C   Kamran     65000

In [38]:
df_01.iloc[0:2, 0:2]

      Name     City
A   Waseem   Quetta
B  Summiya  Karachi

In [25]:
df_01.iloc[0:2]

      Name     City  Salary    Designation
A   Waseem   Quetta   65000  Web-Developer
B  Summiya  Karachi   70000         Doctor

In [24]:
df_01.iloc[0, 0]     # First row, first column

'Waseem'

In [39]:
df_01.iloc[-1]   # last row

Name                          Talha
City                        Kuchlak
Salary                        65000
Designation    Mobile App Developer
Name: D, dtype: object

In [40]:
df_01.iloc[0:3:2]   # works

     Name     City    Salary            Designation
A  Waseem   Quetta  20500000          Web-Developer
C  Kamran  Khuzdar     65000  Desktop App Developer

In [52]:
new_data = [
    ["Ahmed", "Turbat", 250000, "Data Scientist"],  
    ["Zain", "Quetta", 180000, "ML Engineer"],
    ["Bilal", "Khuzdar", 120000, "Software Developer"],
    ["Hassan", "Gwadar", 200000, "AI Engineer"]
]
df_02 = pd.DataFrame(new_data, index=index_labels, columns=columns)
df_03 = pd.concat([df_01, df_02])
df_03

      Name     City              Salary            Designation      Age
A   Waseem   Quetta            20500000          Web-Developer      NaN
B  Summiya  Karachi               70000                 Doctor      NaN
C   Kamran  Khuzdar               65000  Desktop App Developer      NaN
D    Talha  Kuchlak               65000   Mobile App Developer      NaN
A    Ahmed   250000      Data Scientist                    NaN   Turbat
B     Zain   180000         ML Engineer                    NaN   Quetta
C    Bilal   120000  Software Developer                    NaN  Khuzdar
D   Hassan   200000         AI Engineer                    NaN   Gwadar

In [ ]:
df_03.describe()

          Name    City  Salary    Designation
count        8       8       8              4
unique       8       8       7              4
top     Waseem  Quetta   65000  Web-Developer
freq         1       1       2              1

In [ ]:
df_03.info()

In [63]:
df_03.drop("Age", axis=1, inplace=True)

KeyError: "['Age'] not found in axis"

In [12]:
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print("Our DataFrame:")
print(df)
print()
print(f"Shape: {df.shape}  →  {df.shape[0]} rows, {df.shape[1]} columns")

Our DataFrame:
   calories  duration
0       420        50
1       380        40
2       390        45

Shape: (3, 2)  →  3 rows, 2 columns

---
## 📍 Selecting Rows with `.loc[]`

`.loc[]` selects rows by their **index label**.

By default the labels are 0, 1, 2... but later we'll give them custom names like "Day 1", "Day 2".

### 🏠 Analogy
`.loc[]` is like finding a person by their **name** in a contact list. You say "give me the row labeled **0**".

In [ ]:
# Get a single row by its label
print("Row at label 0:")
print(df.loc[0])
print()
print("Row at label 1:")
print(df.loc[1])

In [ ]:
# Get MULTIPLE rows — pass a range
# IMPORTANT: df.loc[0:1] includes BOTH 0 and 1 (unlike normal Python slicing!)
print("Rows 0 and 1 (both included):")
print(df.loc[0:1])
print()
print("⚠️  Note: df.loc[0:1] gives 2 rows (0 AND 1). In regular Python, 0:1 would only give index 0!")

### 🎯 Getting a Specific Cell

You can pinpoint an exact cell using `.loc[row, column]`.

Like GPS coordinates — row first, then column.

In [ ]:
# df.loc[row_label, column_name]
print(f"Row 0, calories column: {df.loc[0, 'calories']}")
print(f"Row 1, duration column: {df.loc[1, 'duration']}")
print()
print("Full table for reference:")
print(df)

---
## 🔎 Filtering Rows by Condition

This is one of the most useful features in Pandas — filter rows based on a condition, like asking: **"show me only rows where calories == 420"**.

### 🏠 Analogy
Like using a filter in Excel — you click the dropdown and say "show me only rows where calories > 385". Pandas does this with one line of code.

In [1]:
# Filter: only rows where calories == 420
print("Rows where calories == 420:")
print(df.loc[df['calories'] == 420])
print()

# Filter: only rows where calories > 385
print("Rows where calories > 385:")
print(df.loc[df['calories'] > 385])
print()
print("💡 How this works internally:")
print("  df['calories'] > 385  produces:", list(df['calories'] > 385))
print("  → True/False for each row. .loc[] keeps only the True rows.")

Rows where calories == 420:

NameError: name 'df' is not defined

---
## 🔢 Selecting by Position with `.iloc[]`

`.iloc[]` selects by **position** — always 0, 1, 2... regardless of what the index labels are.

### `.loc[]` vs `.iloc[]` — What's the difference?

```python
# If your DataFrame has custom labels like "Day 1", "Day 2":
df.loc["Day 1"]   ✅  finds the row LABELED "Day 1"
df.iloc[0]        ✅  finds the FIRST row (position 0), whatever it's labeled
```

**Use `.iloc[]` when you want to say "give me the 3rd row" regardless of its name.**

In [ ]:
# iloc[0] always = first row (position 0)
print("First row by position (iloc[0]):")
print(df.iloc[0])
print()

# Pick specific rows by position — pass a list
print("Rows at positions [1, 2, 0] — notice custom order:")
print(df.loc[[1, 2, 0]])  # You can even reorder!
print()
print("💡 df.loc[[1,2,0]] lets you pick rows in any order you want")

---
## 🏷️ Named Indexes (Custom Row Labels)

Instead of 0, 1, 2 as row labels, you can give meaningful names like "Day 1", "Day 2", "Day 3".

This makes `.loc[]` much more readable — you access rows by their **meaning**, not just a number.

In [ ]:
data1 = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

# Give each row a meaningful name
newDf = pd.DataFrame(data1, index=["Day 1", "Day 2", "Day 3"])

print("DataFrame with named row indexes:")
print(newDf)
print()

# Now access rows by their name!
print('newDf.loc["Day 2"]:')  
print(newDf.loc["Day 2"])

---
## 📁 Loading a CSV File into a DataFrame

`pd.read_csv()` is how you bring in real-world data. CSV (Comma-Separated Values) is the most common data format — every tool from Excel to databases can export to CSV.

In [ ]:
populationDf = pd.read_csv("./Datasets/population.csv")

print(f"Loaded: {populationDf.shape[0]} rows × {populationDf.shape[1]} columns")
print()
print("First 5 rows:")
populationDf.head()