# EDA Basics

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

### Loading the Datasets

In [2]:
# sns.load_dataset("iris")
# sns.load_dataset("tips")
df = sns.load_dataset("titanic")

### Basic Info

In [6]:
df.info() #  Function/Method Call
# df.info #  Attribute/Property Reference

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [5]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Importing Data Set from W3Schools.com

In [14]:
df_w3 = pd.read_csv("../Datasets/cleaning_dataset.csv")
df_w3

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130     409.1
1         60  2020-12-02    117       145     479.0
2         60  2020-12-03    103       135     340.0
3         45  2020-12-04    109       175     282.4
4         45  2020-12-05    117       148     406.0
5         60  2020-12-06    102       127     300.0
6         60  2020-12-07    110       136     374.0
7        450  2020-12-08    104       134     253.3
8         30  2020-12-09    109       133     195.1
9         60  2020-12-10     98       124     269.0
10        60  2020-12-11    103       147     329.3
11        60  2020-12-12    100       120     250.7
12        60  2020-12-12    100       120     250.7
13        60  2020-12-13    106       128     345.3
14        60  2020-12-14    104       132     379.3
15        60  2020-12-15     98       123     275.0
16        60  2020-12-16     98       120     215.2
17        60  2020-12-17    100       120     300.0
18        45  2020-12-18     90       112       NaN
19        60  2020-12-19    103       123     323.0
20        45  2020-12-20     97       125     243.0
21        60  2020-12-21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020-12-23    130       101     300.0
24        45  2020-12-24    105       132     246.0
25        60  2020-12-25    102       126     334.5
26        60  2020-12-26    100       120     250.0
27        60  2020-12-27     92       118     241.0
28        60  2020-12-28    103       132       NaN
29        60  2020-12-29    100       132     280.0
30        60  2020-12-30    102       129     380.3
31        60  2020-12-31     92       115     243.0

### Find Missing Values / Null Valus (NaNs)

In [10]:
df_cleaned_from_null_values = df_w3.dropna()
df_cleaned_from_null_values

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130     409.1
1         60  2020-12-02    117       145     479.0
2         60  2020-12-03    103       135     340.0
3         45  2020-12-04    109       175     282.4
4         45  2020-12-05    117       148     406.0
5         60  2020-12-06    102       127     300.0
6         60  2020-12-07    110       136     374.0
7        450  2020-12-08    104       134     253.3
8         30  2020-12-09    109       133     195.1
9         60  2020-12-10     98       124     269.0
10        60  2020-12-11    103       147     329.3
11        60  2020-12-12    100       120     250.7
12        60  2020-12-12    100       120     250.7
13        60  2020-12-13    106       128     345.3
14        60  2020-12-14    104       132     379.3
15        60  2020-12-15     98       123     275.0
16        60  2020-12-16     98       120     215.2
17        60  2020-12-17    100       120     300.0
19        60  2020-12-19    103       123     323.0
20        45  2020-12-20     97       125     243.0
21        60  2020-12-21    108       131     364.2
23        60  2020-12-23    130       101     300.0
24        45  2020-12-24    105       132     246.0
25        60  2020-12-25    102       126     334.5
26        60  2020-12-26    100       120     250.0
27        60  2020-12-27     92       118     241.0
29        60  2020-12-29    100       132     280.0
30        60  2020-12-30    102       129     380.3
31        60  2020-12-31     92       115     243.0

### Remove all rows with NULL values:   
If you want to change the original then use inplace=True inside dropna paranthesis

In [12]:
df_w3.dropna(inplace = True)
df_w3

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130     409.1
1         60  2020-12-02    117       145     479.0
2         60  2020-12-03    103       135     340.0
3         45  2020-12-04    109       175     282.4
4         45  2020-12-05    117       148     406.0
5         60  2020-12-06    102       127     300.0
6         60  2020-12-07    110       136     374.0
7        450  2020-12-08    104       134     253.3
8         30  2020-12-09    109       133     195.1
9         60  2020-12-10     98       124     269.0
10        60  2020-12-11    103       147     329.3
11        60  2020-12-12    100       120     250.7
12        60  2020-12-12    100       120     250.7
13        60  2020-12-13    106       128     345.3
14        60  2020-12-14    104       132     379.3
15        60  2020-12-15     98       123     275.0
16        60  2020-12-16     98       120     215.2
17        60  2020-12-17    100       120     300.0
19        60  2020-12-19    103       123     323.0
20        45  2020-12-20     97       125     243.0
21        60  2020-12-21    108       131     364.2
23        60  2020-12-23    130       101     300.0
24        45  2020-12-24    105       132     246.0
25        60  2020-12-25    102       126     334.5
26        60  2020-12-26    100       120     250.0
27        60  2020-12-27     92       118     241.0
29        60  2020-12-29    100       132     280.0
30        60  2020-12-30    102       129     380.3
31        60  2020-12-31     92       115     243.0

### Replace Empty Values

Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value:

In [ ]:
df_w3["Calories"].fillna(df_w3["Calories"].median(), inplace=True)

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18    291.2
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28    291.2
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [24]:
df_w3["Duration"].fillna(df_w3["Duration"].mode()[0], inplace=True)

/tmp/ipykernel_6535/1918797636.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_w3["Duration"].fillna(df_w3["Duration"].mode()[0], inplace=True)

0      60
1      60
2      60
3      45
4      45
5      60
6      60
7     450
8      30
9      60
10     60
11     60
12     60
13     60
14     60
15     60
16     60
17     60
18     45
19     60
20     45
21     60
22     45
23     60
24     45
25     60
26     60
27     60
28     60
29     60
30     60
31     60
Name: Duration, dtype: int64

### Replace NULL values in the "Calories" columns with the number 130:

In [25]:
df_w3.fillna({"Maxpulse": df_w3["Maxpulse"].mode()[0]}, inplace=True)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020-12-01    110       130     409.1
1         60  2020-12-02    117       145     479.0
2         60  2020-12-03    103       135     340.0
3         45  2020-12-04    109       175     282.4
4         45  2020-12-05    117       148     406.0
5         60  2020-12-06    102       127     300.0
6         60  2020-12-07    110       136     374.0
7        450  2020-12-08    104       134     253.3
8         30  2020-12-09    109       133     195.1
9         60  2020-12-10     98       124     269.0
10        60  2020-12-11    103       147     329.3
11        60  2020-12-12    100       120     250.7
12        60  2020-12-12    100       120     250.7
13        60  2020-12-13    106       128     345.3
14        60  2020-12-14    104       132     379.3
15        60  2020-12-15     98       123     275.0
16        60  2020-12-16     98       120     215.2
17        60  2020-12-17    100       120     300.0
18        45  2020-12-18     90       112       NaN
19        60  2020-12-19    103       123     323.0
20        45  2020-12-20     97       125     243.0
21        60  2020-12-21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020-12-23    130       101     300.0
24        45  2020-12-24    105       132     246.0
25        60  2020-12-25    102       126     334.5
26        60  2020-12-26    100       120     250.0
27        60  2020-12-27     92       118     241.0
28        60  2020-12-28    103       132       NaN
29        60  2020-12-29    100       132     280.0
30        60  2020-12-30    102       129     380.3
31        60  2020-12-31     92       115     243.0